from operator import add
from typing import Annotated, Literal

from pydantic import BaseModel, Field


class AgentSchema(BaseModel):
    messages: Annotated[list, add] = Field(
        ..., description="List of messages to be processed by the agent"
    )
    user_question: str = Field(
        ..., description="The original question asked by the user"
    )
    curated_question: str = Field(..., description="Curated user question")
    prompt_query_context: str = Field(
        ...,
        description="A detailed prompt with SQL DB context that will help agent to generate SQL Query",
    )
    generated_sql_query: str = Field(
        ...,
        description="The SQL query generated by the agent based on the curated question and prompt context",
    )
    is_safe: Literal["Yes", "No"] = Field(
        ...,
        description="Indicates whether the generated SQL query is safe to execute or not",
    )
    comments: str = Field(
        ..., description="Comments regarding the safety of the generated SQL query"
    )
    sql_query_execution_result: str = Field(
        ...,
        description="The result of executing the generated SQL query on the database",
    )
    final_answer: str = Field(
        ...,
        description="The final answer generated by the agent based on the SQL query execution result and the curated question",
    )


class JudgeSchema(BaseModel):
    answer: Literal["Yes", "No"] = Field(
        ...,
        description="Indicates whether the generated SQL query is safe to execute or not",
    )
    comments: str = Field(
        ...,
        description="Additional comments or feedback from the judge regarding the SQL query",
    )


class ETLAgentSchema(BaseModel):
    messages: Annotated[list, add] = Field(
        ..., description="List of messages to be processed by the ETL agent"
    )


class TransformationStep(BaseModel):
    operation: Literal[
        "filter_equals",
        "filter_contains",
        "select_columns",
        "sort",
        "limit",
    ]
    column: str | None = None
    value: str | int | float | bool | None = None
    columns: list[str] = Field(default_factory=list)
    ascending: bool = True
    limit: int | None = Field(default=None, ge=1, le=100000)


class TransformationPlan(BaseModel):
    steps: list[TransformationStep] = Field(default_factory=list, max_length=10)


class RouterSchema(BaseModel):
    answer: Literal["sql", "etl"] = Field(
        ...,
        description="Indicates whether the user's question is related to SQL or ETL operations",
    )
    comments: str = Field(
        ...,
        description="Additional comments or feedback regarding the classification of the user's question",
    )


class DataAgentSchema(BaseModel):
    messages: Annotated[list, add] = Field(
        ..., description="List of messages to be processed by the Data agent"
    )
    route_response: Literal["sql", "etl"] | None = Field(
        default=None,
        description="The response from the router indicating whether to route to SQL or ETL operations",
    )
